### ISSUE TITLE
Actividades

### ISSUE THREAD

**Issue by jesmg** [UNIA-ALMERIA/unia-almeria.github.io#2]
Hay que testear si, al añadir el _draft de una nueva actividad, se postea correctamente en la cateogoría UNIA del foro de HLAlmeria

**Comment by jpramez** [comment]
Confirmado, la actividad genera su propia pagina al añadir en una carpeta "_posts" un documento en 'Markdown' formateado de la sguiente manera: "aaaa-mm-dd-titulo.md"

**Comment by jesmg** [comment]
¿Pero crea un mensaje en la categoría UNIA del foro de Hacklab?

**Comment by jpramez** [comment]
No, crea una Actividad en el apartado "actividades" de la web de unia

**Comment by jesmg** [comment]
Hace falta lo otro también. Es la razón del issue

2015-09-07 20:53 GMT+02:00 Juan Pedro Ramos Gómez notifications@github.com
:

**Comment by jpramez** [comment]
Pero los posts no se crean directamente en el Foro? El tema actividades no va a parte?

**Comment by jesmg** [comment]
Que yo sepa, se crea automaticamente

2015-09-07 20:58 GMT+02:00 Juan Pedro Ramos Gómez notifications@github.com
:

**Comment by jesmg** [comment]
Es más, creo que vi algo de config al respecto por los archivos

**Comment by olea** [comment]
Si estáis hablando de que una nueva actividad en la web de UNIA cree una nueva entrada otomáticamente en el foro, como ocurre con la web del HLA debo deciros que desgraciadamente no puede funcionar así porque Discourse sólo incorpora la funcionalidad para una única fuente RSS que es la que se está usando ahora.

Es posible que pueda programarse algo adhoc tirando de los webhooks de Discourse.

Cierro el boletín pq creo que la cosa está respondida. Si alguien quiere atreverse a hacer el webhook que lo reabra o que cree uno nuevo y se lo autoasigna.
